version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  test:
    jobs:
      - cypress/run:
          package-manager: 'yarn'
          start-command: 'yarn start'
          cypress-command: 'npx cypress run --browser chrome'
